service/src/integration-test/resources/fhir/encounter_valid.json, service/src/integration-test/resources/xml/ITK_Report_request.xml, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AuthorMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DataEntererMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/InformantMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ParticipantMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PeriodMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleService.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AuthorMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DataEntererMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/InformantMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ParticipantMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleServiceTest.java, service/src/test/resources/xml/ITK_Report_request.xml
encounter participant seems to be related to episodeOfCare, so we need to map participant1
=> NIAD-278: prepared alternative version of encounter participant mapper

README.md
Adding ActiveMQ to the README file
=> Removing last reference to RabbitMQ from the README

service/src/integration-test/resources/xml/ITK_Report_request.xml, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DiagnosisMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DiagnosisMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java
=> NIAD-293: Map ITK Report -> FHIR Encounter.Diagnosis

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AddressMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AppointmentMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/CarePlanMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/CompositionMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HumanNameMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/LocationMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PatientMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ReferralRequestMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ServiceProviderMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleService.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/util/NodeUtil.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AddressMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/AppointmentMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/CarePlanMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/CompositionMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HumanNameMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/LocationMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PatientMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ReferralRequestMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ServiceProviderMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleServiceTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/util/NodeUtilTest.java
Initial commit, healtchcareservice refactored for list, encounter and referral refactored to pass healthcareservice from bundlereport, healthcare add to bundle, nodeutil changed to spring component for unit test, int test refactored for healthcare service
=> NIAD-353: Map ITK Report to FHIR HealthcareService

service/src/integration-test/resources/xml/ITK_Report_request.xml, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java
Initial commit, missing fields type and reason added to encounterMapper unit tests refactored for new values with mocks
=> NIAD-294: Map ITK Report to FHIR CareConnect-Encounter Simple Fields

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/InformantMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapper.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapperTest.java
- Initial commit to allow rebasing to master
- Refactor the original idea by using the practionerMatcher and
informantMapper.
- Also had to update the matcher to accept RelatedSubject.
=> NIAD-354: Mapping ITK Report to FHIR RelatedPerson

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DiagnosisMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleService.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/DiagnosisMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/service/EncounterReportBundleServiceTest.java
Condition mapping complete with unit test and int test refactor, condition now added to bundle.
=> NIAD-352: Map ITK Report -> FHIR Condition

service/src/integration-test/resources/xml/ITK_Report_request.xml, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/InformantMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ParticipantMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapper.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/RelatedPersonMapper.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PractitionerMapperTest.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/RelatedPersonTest.java
Removed duplicated participant from previous pr, added effective time to related entity in ITK report, created Relatedperson mapper plus unit tests, added relatedpersonmapper to participantMapper, add this new praticipantmapper method to encounter to add related person. Related person now exists in bundle
=> NIAD-354: Map ITK Report -> FHIR RelatedPerson

README.md, example_FHIR_bundle_message.json
Readme updated for example bundle message and bundle message added as json file
=> NIAD-403: Upload example FHIR message to github

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportController.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/exceptions/ItkXmlException.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/exceptions/SoapClientException.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ItkResponseUtil.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ReportElement.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ReportParserUtil.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ReportRequestUtils.java, service/src/main/resources/application.yml, service/src/main/resources/itk/SoapItkErrorResponseTemplate.xml, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ItkResponseUtilTest.java
Soap error response created, additional error handling for internal errors, extract address from report element, additional error handling for missing soap headers and body elements
=> NIAD-343: Error Handling

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportController.java, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ItkResponseUtil.java
Original message id and new message id order fixed and default address return instead of null for xml error.
=> NIAD-343: Error Handling Fix

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportController.java
Missing message id and address added to soapclientexception
=> NIAD-343: Error Handling SoapClientException missing address and messageid fix

service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportController.java, service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/controller/utils/ItkResponseUtilTest.java
Checkstyle test fix and returning default address and message id f instead of null in response
=> NIAD-343: Error handling checkstyle fix

test-scripts/0.1.0/docker-compose.yml, test-scripts/0.1.0/run.sh
Latest changes for the docker release
=> Changes to test-scripts

service/build.gradle, service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/validation/ItkValidator.java
=> NIAD-1573 audit identity validation

Jenkinsfile
TF binaries to be used to deploy TF code is controlled via version file containing version  number. On pipeline execution, TF binary of relevant version number will be downloaded and execution path is set.
=> Update TF Binaries with Path Set

README.md, nhs-england-developer-information.md
_See individual commits for details_
=> Improvements to the main README.md documentation

service/build.gradle
This brings in a lot of fixes, however we'll still need to update to the 3.* branch at some point.
=> Upgrade Spring boot to the latest 2.* version

service/src/integration-test/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportControllerIT.java
See also:
https://docs.spring.io/spring-boot/docs/2.7.18/api/org/springframework/boot/web/server/LocalServerPort.html
=> Fix deprecated LocalServerPort in favour of replacement

.github/workflows/release.yml, scripts/config/.syft.yaml, scripts/sbom-generator.sh
* Update release.yaml use new release pattern and to provide the upload url to attach the SBOM to the release.
* Add the files needed to generate the SBOM.
This is required as part of the GitHub best practices.
=> NIAD-3394: Update release workflow to generate SBOM
